# Generated by Django 5.2.5 on 2025-08-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField()),
                ('receiver_card_number', models.CharField()),
                ('sender_card_number', models.CharField()),
                ('otp', models.CharField(help_text='6-digit OTP code sent for confirmation')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ['ext_id'],
            },
        ),
    ]
